[[main]]
  name = "home"
  url = "#home"
  weight = 10

[[main]]
  name = "posts"
  url = "post"
  weight = 20

[[main]]
  name = "whoswho"
  url = "https://whoswho.astrogewgaw.com"
  weight = 30

[[main]]
  name = "about"
  url = "#about"
  weight = 40

[[main]]
  name = "github"
  url = "https://github.com/astrogewgaw/"
  weight = 50

[[main]]
  name = "twitter"
  url = "https://twitter.com/astrogewgaw/"
  weight = 60

[[main]]
  name = "cv"
  url = "files/CV.pdf"
  weight = 70
